[workspace]
members = ["niri-config", "niri-ipc"]

[workspace.package]
version = "26.4.0"
description = "[ALL CREDITS TO YaLTeR] A scrollable-tiling Wayland compositor (takashialpha's personal fork!)"
authors = [
  "Ivan Molodetskikh <yalterz@gmail.com>",
  "takashialpha <takashialpha@protonmail.com>",
]
license = "GPL-3.0-or-later"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0"
bitflags = "2.13"
clap = { version = "4.6", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = { version = "0.1", features = [
  "max_level_trace",
  "release_max_level_debug",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[workspace.dependencies.smithay]
git = "https://github.com/Smithay/smithay.git"
rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef"
default-features = false

[workspace.dependencies.smithay-drm-extras]
git = "https://github.com/Smithay/smithay.git"
rev = "ff5fa7df392cecfba049ffed55cdaa4e98a8e7ef"

[package]
name = "niri"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true

readme = "README.md"
keywords = ["wayland", "compositor", "tiling", "smithay", "wm"]

[dependencies]
anyhow.workspace = true
arrayvec = "0.7" # should analyze
async-channel = "2.5"
atomic = "0.6" # should analyze
bitflags.workspace = true
bytemuck = { version = "1.25", features = ["derive"] }
calloop = { version = "0.14", features = ["executor", "futures-io", "signals"] }
clap = { workspace = true, features = ["string"] }
clap_complete = "4.6" # i see that as useless (and doesn't even work on my shell)
clap_complete_nushell = "4.6" # even more useless
directories = "6.0"
drm-ffi = "0.9"
fastrand = "2.4"
futures-util = { version = "0.3", default-features = false, features = [
  "std",
  "io",
] }
git-version = "0.3"
glam = "0.33"
input = { version = "0.10", features = ["libinput_1_21"] }
keyframe = { version = "1.1", default-features = false }
libc = "0.2" # to rustix!
libdisplay-info = "0.3"
niri-config = { version = "26.4.0", path = "niri-config" }
niri-ipc = { version = "26.4.0", path = "niri-ipc", features = ["clap"] }
ordered-float = "5.3"
pango = { version = "0.22", features = ["v1_44"] }
pangocairo = "0.22"
png = "0.18"
sd-notify = "0.5"
serde_json.workspace = true
smithay-drm-extras.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
wayland-backend = "0.3"
wayland-server = "0.31"
xcursor = "0.3" # e.g of some crates that could be replaced?

[dependencies.smithay]
workspace = true
features = [
  "backend_drm",
  "backend_egl",
  "backend_gbm",
  "backend_libinput",
  "backend_session_libseat",
  "backend_udev",
  "desktop",
  "renderer_gl",
  "renderer_pixman",
  "renderer_multi",
  "use_system_lib",
  "wayland_frontend",
]

[profile.release]
debug = "line-tables-only"
overflow-checks = true
lto = "thin"

[profile.release.package.niri-config]
debug = false # knus .. ?
