[package]
name = "niri-config"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

readme = "../README.md"
keywords = ["wayland", "niri", "config"]
categories = ["config"]

[dependencies]
bitflags.workspace = true
csscolorparser = "0.8"
knus = "3.4"
miette = "7.6"
niri-ipc = { path = "../niri-ipc" }
regex = "1.13"
smithay = { workspace = true, features = ["backend_libinput"] }
tracing.workspace = true
