[package]
name = "niri-ipc"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description.workspace = true
keywords = ["wayland"]
categories = ["api-bindings", "os"]

[dependencies]
clap = { workspace = true }
serde.workspace = true
serde_json.workspace = true
